metadata:
  bergson_version: null
  created: '2026-08-25T03:23:10+00:00'
  git_sha: 79c08dce
  nccl_version: 2.29.3
run_path: /mnt/ssd-2/lucia/paper_runs/experiments/plan_adam_eps1e17_64k_bs256_qswap/magic_scores_q6_7
steps:
- magic:
    adam_beta1: 0.95
    adam_beta2: 0.975
    adam_eps: 1.0e-08
    attribute_tokens: false
    backward_save_every: 0
    batch_size: 256
    cleanup_ckpts: false
    data:
      chunk_length: 0
      completion_column: ''
      conversation_column: ''
      data_kwargs: ''
      dataset: /mnt/ssd-2/lucia/datasets_local/train_64k_qswap.hf
      format_template: ''
      prompt_column: text
      reward_column: ''
      skip_nan_rewards: false
      split: train
      subset: null
      truncation: false
    debug: false
    distributed:
      nnode: 1
      node_rank: null
      nproc_per_node: 4
    double_backward_batch_size: 4
    drop_columns: true
    eps_root: 1.0e-17
    exclude_zero_scores: false
    fsdp: false
    grad_accum_steps: 8
    grad_checkpointing: false
    loss_reduction: mean
    lr_schedule:
      lr: 0.0001
      lr_end: 1.0e-05
      lr_scheduler_type: polynomial
      lr_start: 1.0e-06
      num_cycles: 0.5
      power: 1.0
      warmup_steps: 0.25
    max_grad_norm: null
    max_tokens: null
    model: gpt2
    model_kwargs: resid_pdrop=0.0,attn_pdrop=0.0,embd_pdrop=0.0
    num_epochs: 2
    num_subsets: 0
    optimizer: adamw
    overwrite: false
    peft_init_kwargs: ''
    per_token: false
    precision: fp32
    query:
      chunk_length: 0
      completion_column: ''
      conversation_column: ''
      data_kwargs: ''
      dataset: /mnt/ssd-2/lucia/datasets_local/query_20_q6_7.hf
      format_template: ''
      prompt_column: text
      reward_column: ''
      skip_nan_rewards: false
      split: train
      subset: null
      truncation: false
    query_method: none
    resume: true
    revision: null
    run_path: /mnt/ssd-2/lucia/paper_runs/experiments/plan_adam_eps1e17_64k_bs256_qswap/magic_scores_q6_7
    save_interval: 0
    save_mode: log
    save_models: true
    save_optimizer_state: last
    seed: 42
    skip_validation: true
    subset_fraction: 0.01
    subset_start: 0
    subset_stop: null
    subset_weight: 0.0
    subsets: ''
    tokenizer: ''
    train_mode: false
    use_tf32_matmuls: false
    wandb_project: ''
    weight_decay: 0.01
    weight_lrs: []
