steps:
- validate:
    run_path: runs/lotus_source_adam_q50_validate
    overwrite: true
    model: gpt2
    precision: fp32
    revision: null
    distributed:
      nnode: 1
      nproc_per_node: 8
      node_rank: null
    fsdp: false
    peft_init_kwargs: ''
    model_kwargs: ''
    data:
      dataset: EleutherAI/bergson-wikitext-512-chunks
      split: train
      subset: null
      prompt_column: text
      completion_column: ''
      conversation_column: ''
      reward_column: ''
      skip_nan_rewards: false
      truncation: false
      format_template: ''
      data_kwargs: ''
      chunk_length: 512
    tokenizer: ''
    drop_columns: true
    max_tokens: null
    use_tf32_matmuls: false
    debug: false
    lr_schedule:
      lr: 1.0e-05
      lr_scheduler_type: linear
      lr_start: 0.0
      lr_end: 0.0
      warmup_steps: 0
      num_cycles: 0.5
      power: 1.0
    batch_size: 64
    num_epochs: 1
    seed: 42
    adam_beta1: 0.95
    adam_beta2: 0.975
    eps_root: 1.0e-08
    adam_eps: 1.0e-08
    loss_reduction: mean
    optimizer: adamw
    weight_decay: 0.01
    max_grad_norm: null
    grad_checkpointing: false
    resume: false
    wandb_project: ''
    save_optimizer_state: false
    save_retrained_models: false
    query:
      dataset: EleutherAI/bergson-wikitext-512-chunks
      split: test[1:51]
      subset: null
      prompt_column: text
      completion_column: ''
      conversation_column: ''
      reward_column: ''
      skip_nan_rewards: false
      truncation: false
      format_template: ''
      data_kwargs: ''
      chunk_length: 0
    query_method: mean
    num_subsets: 100
    subset_strategy: random
    exclude_zero_scores: false
    subset_fraction: 0.0
    skip_existing_retrained: false
    scores: runs/lotus_source_adam_q50/scores.npy
    retrained_dir: runs/lotus
metadata:
  bergson_version: 0.10.1
  created: '2026-07-18T04:21:09+00:00'
  git_sha: a7f90f89
