steps:
- validate:
    run_path: /mnt/ssd-2/lucia-adam-shampoo/shampoo_adam/validate
    model: gpt2
    overwrite: true
    scores: /mnt/ssd-2/lucia-adam-shampoo/shampoo_adam/scores/scores
    retrained_dir: /mnt/ssd-2/lucia-adam-shampoo/run_adam/N4k
    data:
      dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/train_4k.hf
      split: train
      chunk_length: 0
    query:
      dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/query_50.hf
      split: train
      chunk_length: 0
    batch_size: 50
