run_path: /mnt/ssd-2/lucia/paper_runs/tuning/tune_adamw_16k_bs32_lr5e-05_s42
steps:
- train:
    run_path: /mnt/ssd-2/lucia/paper_runs/tuning/tune_adamw_16k_bs32_lr5e-05_s42
    overwrite: true
    model: gpt2
    model_kwargs: resid_pdrop=0.0,attn_pdrop=0.0,embd_pdrop=0.0
    precision: fp32
    use_tf32_matmuls: false
    distributed:
      nnode: 1
      nproc_per_node: 2
    data:
      dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/train_16k.hf
      split: train
      chunk_length: 0
    lr_schedule:
      lr: 5.0e-05
      lr_scheduler_type: polynomial
      lr_start: 1.0e-06
      lr_end: 5.0e-06
      warmup_steps: 0.25
    batch_size: 32
    grad_accum_steps: 1
    num_epochs: 2
    seed: 42
    optimizer: adamw
    adam_beta1: 0.95
    adam_beta2: 0.975
    adam_eps: 1.0e-08
    eps_root: 1.0e-17
    weight_decay: 0.01
    loss_reduction: mean
    train_mode: false
    save_models: true
    save_optimizer_state: none
    save_mode: interval
    save_interval: 1000000000
