run_path: /mnt/ssd-2/lucia/paper_runs/tuning/tune_adamw_london32k_bs256_lr0.0008_s42
steps:
- train:
    adam_beta1: 0.95
    adam_beta2: 0.975
    adam_eps: 1.0e-08
    batch_size: 256
    data:
      chunk_length: 0
      dataset: /mnt/ssd-2/lucia/datasets_local/london_32k.hf
      split: train
    distributed:
      nnode: 1
      nproc_per_node: 2
    eps_root: 1.0e-17
    grad_accum_steps: 8
    loss_reduction: mean
    lr_schedule:
      lr: 0.0008
      lr_end: 8.0e-05
      lr_scheduler_type: polynomial
      lr_start: 1.0e-06
      warmup_steps: 0.25
    model: gpt2
    model_kwargs: resid_pdrop=0.0,attn_pdrop=0.0,embd_pdrop=0.0
    num_epochs: 2
    optimizer: adamw
    overwrite: true
    precision: fp32
    run_path: /mnt/ssd-2/lucia/paper_runs/tuning/tune_adamw_london32k_bs256_lr0.0008_s42
    save_interval: 1000000000
    save_mode: interval
    save_models: true
    save_optimizer_state: none
    seed: 42
    train_mode: false
    use_tf32_matmuls: false
    weight_decay: 0.01
