run_path: /mnt/ssd-2/lucia/muon4k/ekfac_adam_eps1e8/pipeline
steps:
- ekfac:
    index_cfg:
      run_path: /mnt/ssd-2/lucia/muon4k/ekfac_adam_eps1e8/scores
      model: /mnt/ssd-2/lucia/muon4k/adam_eps1e8/N4k/retrained/base
      overwrite: true
      projection_dim: 0
      token_batch_size: 1024
      max_batch_size: 64
      filter_modules: lm_head
      distributed:
        nproc_per_node: 1
        nnode: 1
      data: &id001
        dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/train_4k.hf
        split: train
        chunk_length: 0
    hessian_cfg:
      method: kfac
      ev_correction: true
    score_cfg:
      batch_size: 1024
    preprocess_cfg:
      unit_normalize: false
    hessian_pipeline_cfg:
      query: &id002
        dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/query_50.hf
        split: train
        chunk_length: 0
      query_aggregation: none
      inversion_cfg:
        damping_factor: 0.1
      resume: false
- validate:
    run_path: /mnt/ssd-2/lucia/muon4k/ekfac_adam_eps1e8/validate
    model: gpt2
    overwrite: true
    scores: /mnt/ssd-2/lucia/muon4k/ekfac_adam_eps1e8/scores/scores
    retrained_dir: /mnt/ssd-2/lucia/muon4k/adam_eps1e8/N4k
    num_subsets: 100
    data: *id001
    query: *id002
    batch_size: 50
