steps:
- validate:
    run_path: /mnt/ssd-2/lucia/paper_runs/experiments/qwen15b_64k_bs256/filter_top200_ekfac_q16_17
    overwrite: false
    model: /mnt/ssd-2/lucia/models/Qwen2.5-1.5B
    precision: bf16
    revision: null
    distributed:
      nnode: 1
      nproc_per_node: 2
      node_rank: null
    fsdp: false
    peft_init_kwargs: ''
    model_kwargs: ''
    logit_scale: 1.0
    data:
      dataset: /mnt/ssd-2/lucia/datasets_local/train_64k_qwen.hf
      split: train
      subset: null
      prompt_column: text
      completion_column: ''
      conversation_column: ''
      reward_column: ''
      skip_nan_rewards: false
      truncation: false
      format_template: ''
      data_kwargs: ''
      chunk_length: 0
    tokenizer: ''
    drop_columns: true
    max_tokens: null
    use_tf32_matmuls: false
    debug: false
    lr_schedule:
      lr: 5.0e-05
      lr_scheduler_type: polynomial
      lr_start: 1.0e-06
      lr_end: 5.0e-06
      warmup_steps: 0.25
      num_cycles: 0.5
      power: 1.0
    batch_size: 256
    num_epochs: 2
    seed: 42
    adam_beta1: 0.95
    adam_beta2: 0.975
    eps_root: 1.0e-17
    adam_eps: 1.0e-08
    loss_reduction: mean
    optimizer: adamw
    train_mode: false
    save_optimizer_state: none
    save_models: false
    save_mode: interval
    save_interval: 1000000000
    weight_decay: 0.01
    max_grad_norm: null
    grad_checkpointing: false
    grad_accum_steps: 64
    double_backward_batch_size: null
    resume: true
    wandb_project: ''
    query:
      dataset: /mnt/ssd-2/lucia/datasets_local/query_20_qwen_q16_17.hf
      split: train
      subset: null
      prompt_column: text
      completion_column: ''
      conversation_column: ''
      reward_column: ''
      skip_nan_rewards: false
      truncation: false
      format_template: ''
      data_kwargs: ''
      chunk_length: 0
    query_method: none
    num_subsets: 0
    subset_weight: 0.0
    weight_lrs: []
    exclude_zero_scores: false
    subsets: ''
    subset_start: 0
    subset_stop: null
    subset_fraction: 0.003125
    method: filter-proponents
    scores: /mnt/ssd-2/lucia/paper_runs/experiments/qwen15b_64k_bs256/scores64_q16_17
    retrained_dir: ''
    baseline_model: ''
metadata:
  bergson_version: null
  created: '2026-09-05T00:12:21+00:00'
  git_sha: 7641766f
  nccl_version: 2.29.3
