run_path: /mnt/ssd-2/lucia/paper_runs/experiments/plan_adam_eps1e17_32k_bs256/filter_proponents_bm25_heldout_q12_16
steps:
- validate:
    adam_beta1: 0.95
    adam_beta2: 0.975
    adam_eps: 1.0e-08
    batch_size: 256
    data:
      chunk_length: 0
      dataset: /mnt/ssd-2/lucia/datasets_local/train_32k.hf
      split: train
    distributed:
      nnode: 1
      nproc_per_node: 2
    eps_root: 1.0e-17
    grad_accum_steps: 8
    loss_reduction: mean
    lr_schedule:
      lr: 0.0002
      lr_end: 2.0e-05
      lr_scheduler_type: polynomial
      lr_start: 1.0e-06
      warmup_steps: 0.25
    method: filter-proponents
    model: gpt2
    model_kwargs: resid_pdrop=0.0,attn_pdrop=0.0,embd_pdrop=0.0
    num_epochs: 2
    num_subsets: 3
    optimizer: adamw
    precision: fp32
    query:
      chunk_length: 0
      dataset: /mnt/ssd-2/lucia/datasets_local/query_20_heldout_q12_16.hf
      split: train
    query_method: none
    run_path: /mnt/ssd-2/lucia/paper_runs/experiments/plan_adam_eps1e17_32k_bs256/filter_proponents_bm25_heldout_q12_16
    save_interval: 1000000000
    save_mode: interval
    scores: /mnt/ssd-2/lucia/paper_runs/experiments/plan_adam_eps1e17_32k_bs256/bm25ho_scores_q12_16
    seed: 42
    subset_fraction: 0.01
    use_tf32_matmuls: false
    weight_decay: 0.01
    resume: true
