steps:
- magic:
    run_path: /mnt/ssd-2/lucia/muon4k/sweep/lr2e-5/N4k
    model: gpt2
    overwrite: true
    cleanup_ckpts: true
    data:
      dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/train_4k.hf
      split: train
      chunk_length: 0
    query:
      dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/query_50.hf
      split: train
      chunk_length: 0
    distributed:
      nproc_per_node: 8
      nnode: 1
    eps_root: 1.0e-06
    optimizer: muon
    weight_decay: 0.01
    compile: false
    attn_implementation: eager
    batch_size: 64
    num_epochs: 4
    lr_schedule:
      lr_scheduler_type: polynomial
      lr: 2.0e-05
      lr_start: 1.0e-06
      lr_end: 2.0000000000000003e-06
      warmup_steps: 0.25
    subset_strategy: random
    num_subsets: 1
    subset_fraction: 0.01
    save_optimizer_state: false
    save_retrained_models: true
    skip_metagradient: true
