#!/usr/bin/env python3
"""AdamW vs Muon at 4k-32k documents: QLD and LDS side by side, as a LaTeX table.

    python scripts/qld_lds_table.py            # -> tables/qld_lds_adamw_muon.tex

Replaces the corpus-scaling panel that used to sit in figures/filter_muon_appendix.pdf
(dropped 2026-09-05). Every number is read from experiments.csv, so the table
regenerates with the CSV; nothing is typed in.

Columns:  documents, training tokens (2 epochs x N x 512), optimizer,
          QLD (EK-FAC top-1% filter, filter_ekfac_delta with its 95% CI),
          LDS for EK-FAC and for MAGIC (ekfac_lds / magic_lds with their CIs).
Rows:     bs256 rows only, N <= 32k, the same run selection as scaling_plot_mpl.py
          (the Muon 4k row is the lr 2e-4 re-run, which has a QLD but no LDS; an
          empty cell is printed as -- rather than filled from the older run).

Paste the file into Overleaf with \\input{tables/qld_lds_adamw_muon} inside a
table environment; it needs \\usepackage{booktabs}.
"""
import csv
import os
import pathlib

import absolute_losses as absl  # STAT / qld_from_summary: the QLD_STAT=median column

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = pathlib.Path(os.environ.get("TABLES_DIR") or ROOT / "tables") / "qld_lds_adamw_muon.tex"
NS = [4000, 8000, 16000, 32000]
SERIES = [("AdamW", ("plan_adam_eps1e17_", "sm_adamw_eps1e17_")),
          ("Muon", ("plan_muon_eps1e17_", "sm_muon_eps1e17_"))]
PREFER = ("plan_muon_eps1e17_4k_bs256_lr2e-4",)   # as scaling_plot_mpl.py
tokens = lambda n: 2 * n * 512

rows = list(csv.DictReader(open(ROOT / "experiments.csv", newline="")))


def pick(prefixes, n):
    """Mirror of scaling_plot_mpl.pick_scaling: bs256 rows, PREFER first."""
    for r in sorted(rows, key=lambda r: r["run_id"] not in PREFER):
        rid = r["run_id"]
        if not (rid.endswith("_bs256") or "_bs256_" in rid) or not rid.startswith(prefixes):
            continue
        try:
            if int(float(r["n_docs"])) == n:
                return r
        except (TypeError, ValueError):
            pass
    return None


def cell(r, val, lo, hi, digits):
    """'value [lo, hi]' or '--' when the value is blank."""
    v = (r.get(val) or "").strip()
    if not v:
        return "--"
    if val == "filter_ekfac_delta" and absl.STAT != "mean":
        # experiments.csv holds only the mean: recompute from the merged summary
        p = absl.qld_from_summary(r["run_id"], "filter_proponents_ekfac")
        if p is not None:
            d, l, h = p
            return f"{d:.{digits}f} [{d - l:.{digits}f}, {d + h:.{digits}f}]"
        print(f"  warning: {r['run_id']}/filter_proponents_ekfac: no complete summary, "
              f"{absl.STAT} cell falls back to the experiments.csv mean")
    out = f"{float(v):.{digits}f}"
    l, h = (r.get(lo) or "").strip(), (r.get(hi) or "").strip()
    if l and h:
        out += f" [{float(l):.{digits}f}, {float(h):.{digits}f}]"
    return out


lines = [
    r"% generated by scripts/qld_lds_table.py from experiments.csv -- do not edit by hand",
    r"\begin{tabular}{rrlrrr}",
    r"\toprule",
    r"Documents & Tokens & Optimizer & QLD (nats) & LDS, EK-FAC & LDS, MAGIC \\",
    r"\midrule",
]
missing = []
for n in NS:
    for i, (name, prefixes) in enumerate(SERIES):
        r = pick(prefixes, n)
        if r is None:
            missing.append((n, name))
            continue
        docs = f"{n // 1000}k" if i == 0 else ""
        tok = f"{tokens(n) / 1e6:.0f}M" if i == 0 else ""
        lines.append(" & ".join([
            docs, tok, name,
            cell(r, "filter_ekfac_delta", "filter_ekfac_lo", "filter_ekfac_hi", 3),
            cell(r, "ekfac_lds", "ekfac_ci_lo", "ekfac_ci_hi", 2),
            cell(r, "magic_lds", "magic_ci_lo", "magic_ci_hi", 2),
        ]) + r" \\")
        print(f"  {n // 1000:>3}k {name:6s} {r['run_id']:36s} {lines[-1]}")
    if n != NS[-1]:
        lines.append(r"\addlinespace")
lines += [r"\bottomrule", r"\end{tabular}"]

OUT.parent.mkdir(exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
if missing:
    raise SystemExit(f"no bs256 row for {missing}")
