steps:
- metasmoothness:
    run_path: /mnt/ssd-1/lucia/bergson-ms-pretrain/runs/pretrain_metasmoothness/window_0.6
    model: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/olmo2_reinit
    overwrite: true
    fsdp: false
    use_tf32_matmuls: false
    data:
      dataset: /mnt/ssd-1/lucia/bergson-damping/runs/ekfac_vs_n/datasets/train_16k.hf
      split: train
      chunk_length: 0
    distributed:
      nproc_per_node: 8
      nnode: 1
    optimizer: muon
    weight_decay: 0.1
    eps_root: 1.0e-06
    batch_size: 128
    num_epochs: 6
    weight_start_frac: 0.6
    lr_schedule:
      lr_scheduler_type: polynomial
      lr: 0.009
      lr_start: 1.0e-06
      lr_end: 0.0009
      warmup_steps: 0.25
    fd_step: 0.1
    direction_seed: 0
