steps:
- metasmoothness:
    run_path: /mnt/ssd-2/lucia/muon4k/metasmooth_wikitext_lotus
    overwrite: true
    model: gpt2
    precision: fp32
    revision: null
    distributed:
      nnode: 1
      nproc_per_node: 8
      node_rank: null
    fsdp: false
    peft_init_kwargs: ''
    model_kwargs: ''
    attn_implementation: eager
    compile: false
    data:
      dataset: EleutherAI/bergson-wikitext-512-chunks
      split: train
      subset: null
      prompt_column: text
      completion_column: ''
      conversation_column: ''
      reward_column: ''
      skip_nan_rewards: false
      truncation: false
      format_template: ''
      data_kwargs: ''
      chunk_length: 0
    tokenizer: ''
    drop_columns: true
    max_tokens: null
    use_tf32_matmuls: false
    debug: false
    lr_schedule:
      lr: 0.0008
      lr_scheduler_type: polynomial
      lr_start: 1.0e-06
      lr_end: 8.0e-05
      warmup_steps: 0.25
      num_cycles: 0.5
      power: 1.0
    batch_size: 64
    num_epochs: 4
    seed: 42
    adam_beta1: 0.95
    adam_beta2: 0.975
    eps_root: 1.0e-06
    adam_eps: 1.0e-08
    loss_reduction: mean
    optimizer: adamw
    save_optimizer_state: false
    weight_decay: 0.01
    max_grad_norm: null
    grad_checkpointing: false
    resume: false
    wandb_project: ''
    h: 0.1
    direction_seed: 0
metadata:
  bergson_version: 0.10.0
  created: '2026-07-21T07:39:58+00:00'
  git_sha: a2cd0d3f
